### ISSUE TITLE
move rollup config file to root

### ISSUE THREAD

**Issue by aamir1995** [aaronksaunders/ionic2.0-angularfire#1]
Hi! Thanks for your hard work for community, it is amazing.
The problem is that everytime we have to made changes in rollup config file after pulling from GitHub,
I was wondering if there is any way that we can move rollup config file from `node_modules` to root of project folder and made changes in this file, So we can push it to GitHub :)

**Comment by sudharsanmit** [comment]
@aamir1995  I opened it in issue #2 and suggested the fix also. Pls see if it was what you wanted. I did it and works fine for me.

**Comment by aamir1995** [comment]
@sudharsanmit Thanks for this awesome solution :) I think it will work fine.
